name: Deploy to Azure VM

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.AZURE_SSH_KEY }}

    - name: Deploy via SSH
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.AZURE_USER }}@${{ secrets.AZURE_HOST }} << 'EOF'
          docker stop flask-container || true
          docker rm flask-container || true
          docker rmi flask-app || true
          cd ~/khurram-flask-app
          git pull origin main
          docker build -t flask-app .
          docker run -d -p 80:5000 --name flask-container flask-app
        EOF
