name: Deploy Flask App to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up SSH for deployment
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.AZURE_SSH_KEY }}

      # Step 3: Build Docker Image
      - name: Build Docker Image
        run: docker build -t khuram-flask-app .

      # Step 4: Deploy to Azure VM via SSH
      - name: Deploy to Azure VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.AZURE_USER }}@${{ secrets.AZURE_HOST }} << 'EOF'
          # Stop and remove existing container if running
          docker stop khuram-flask-app || true
          docker rm khuram-flask-app || true
          docker rmi khuram-flask-app || true
          
          # Pull the latest code and rebuild the Docker image
          cd ~/khuram-flask-app
          git pull origin main
          docker build -t khuram-flask-app .

          # Run the Docker container on ports 80 and 8080
          docker run -d -p 80:5000 -p 8080:5000 --name khuram-flask-app khuram-flask-app
          EOF
